# REPLACE the placeholder with your real tunnel URL before running
TUNNEL="https://YOUR_TUNNEL.cloudflare.dev"

cat > shopify.app.toml <<EOF
name = "AI Avatar Talking by Vista"
client_id = "9a3ccdfb354e6d1741a4db9dbcbca2cf"
application_url = "${TUNNEL}"
embedded = true
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "${TUNNEL}/auth/callback"
]
EOF

nl -ba shopify.app.toml
